/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoreOnlySetupRouteImport } from './routes/score-only.setup'
import { Route as ScoreOnlyLiveRouteImport } from './routes/score-only.live'
import { Route as GameSetupRouteImport } from './routes/game.setup'
import { Route as GameLiveRouteImport } from './routes/game.live'
import { Route as FanviewSessionIdRouteImport } from './routes/fanview.$sessionId'
import { Route as FanviewScoreSessionIdRouteImport } from './routes/fanview-score.$sessionId'
import { Route as GameReportSessionIdRouteImport } from './routes/game.report.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreOnlySetupRoute = ScoreOnlySetupRouteImport.update({
  id: '/score-only/setup',
  path: '/score-only/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreOnlyLiveRoute = ScoreOnlyLiveRouteImport.update({
  id: '/score-only/live',
  path: '/score-only/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSetupRoute = GameSetupRouteImport.update({
  id: '/game/setup',
  path: '/game/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLiveRoute = GameLiveRouteImport.update({
  id: '/game/live',
  path: '/game/live',
  getParentRoute: () => rootRouteImport,
} as any)
const FanviewSessionIdRoute = FanviewSessionIdRouteImport.update({
  id: '/fanview/$sessionId',
  path: '/fanview/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const FanviewScoreSessionIdRoute = FanviewScoreSessionIdRouteImport.update({
  id: '/fanview-score/$sessionId',
  path: '/fanview-score/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameReportSessionIdRoute = GameReportSessionIdRouteImport.update({
  id: '/game/report/$sessionId',
  path: '/game/report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/modes': typeof ModesRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/fanview-score/$sessionId': typeof FanviewScoreSessionIdRoute
  '/fanview/$sessionId': typeof FanviewSessionIdRoute
  '/game/live': typeof GameLiveRoute
  '/game/setup': typeof GameSetupRoute
  '/score-only/live': typeof ScoreOnlyLiveRoute
  '/score-only/setup': typeof ScoreOnlySetupRoute
  '/game/report/$sessionId': typeof GameReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/modes': typeof ModesRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/fanview-score/$sessionId': typeof FanviewScoreSessionIdRoute
  '/fanview/$sessionId': typeof FanviewSessionIdRoute
  '/game/live': typeof GameLiveRoute
  '/game/setup': typeof GameSetupRoute
  '/score-only/live': typeof ScoreOnlyLiveRoute
  '/score-only/setup': typeof ScoreOnlySetupRoute
  '/game/report/$sessionId': typeof GameReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/modes': typeof ModesRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/fanview-score/$sessionId': typeof FanviewScoreSessionIdRoute
  '/fanview/$sessionId': typeof FanviewSessionIdRoute
  '/game/live': typeof GameLiveRoute
  '/game/setup': typeof GameSetupRoute
  '/score-only/live': typeof ScoreOnlyLiveRoute
  '/score-only/setup': typeof ScoreOnlySetupRoute
  '/game/report/$sessionId': typeof GameReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/modes'
    | '/roster'
    | '/settings'
    | '/fanview-score/$sessionId'
    | '/fanview/$sessionId'
    | '/game/live'
    | '/game/setup'
    | '/score-only/live'
    | '/score-only/setup'
    | '/game/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/modes'
    | '/roster'
    | '/settings'
    | '/fanview-score/$sessionId'
    | '/fanview/$sessionId'
    | '/game/live'
    | '/game/setup'
    | '/score-only/live'
    | '/score-only/setup'
    | '/game/report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/modes'
    | '/roster'
    | '/settings'
    | '/fanview-score/$sessionId'
    | '/fanview/$sessionId'
    | '/game/live'
    | '/game/setup'
    | '/score-only/live'
    | '/score-only/setup'
    | '/game/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ModesRoute: typeof ModesRoute
  RosterRoute: typeof RosterRoute
  SettingsRoute: typeof SettingsRoute
  FanviewScoreSessionIdRoute: typeof FanviewScoreSessionIdRoute
  FanviewSessionIdRoute: typeof FanviewSessionIdRoute
  GameLiveRoute: typeof GameLiveRoute
  GameSetupRoute: typeof GameSetupRoute
  ScoreOnlyLiveRoute: typeof ScoreOnlyLiveRoute
  ScoreOnlySetupRoute: typeof ScoreOnlySetupRoute
  GameReportSessionIdRoute: typeof GameReportSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-only/setup': {
      id: '/score-only/setup'
      path: '/score-only/setup'
      fullPath: '/score-only/setup'
      preLoaderRoute: typeof ScoreOnlySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-only/live': {
      id: '/score-only/live'
      path: '/score-only/live'
      fullPath: '/score-only/live'
      preLoaderRoute: typeof ScoreOnlyLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/setup': {
      id: '/game/setup'
      path: '/game/setup'
      fullPath: '/game/setup'
      preLoaderRoute: typeof GameSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/live': {
      id: '/game/live'
      path: '/game/live'
      fullPath: '/game/live'
      preLoaderRoute: typeof GameLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fanview/$sessionId': {
      id: '/fanview/$sessionId'
      path: '/fanview/$sessionId'
      fullPath: '/fanview/$sessionId'
      preLoaderRoute: typeof FanviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fanview-score/$sessionId': {
      id: '/fanview-score/$sessionId'
      path: '/fanview-score/$sessionId'
      fullPath: '/fanview-score/$sessionId'
      preLoaderRoute: typeof FanviewScoreSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/report/$sessionId': {
      id: '/game/report/$sessionId'
      path: '/game/report/$sessionId'
      fullPath: '/game/report/$sessionId'
      preLoaderRoute: typeof GameReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ModesRoute: ModesRoute,
  RosterRoute: RosterRoute,
  SettingsRoute: SettingsRoute,
  FanviewScoreSessionIdRoute: FanviewScoreSessionIdRoute,
  FanviewSessionIdRoute: FanviewSessionIdRoute,
  GameLiveRoute: GameLiveRoute,
  GameSetupRoute: GameSetupRoute,
  ScoreOnlyLiveRoute: ScoreOnlyLiveRoute,
  ScoreOnlySetupRoute: ScoreOnlySetupRoute,
  GameReportSessionIdRoute: GameReportSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
